### ISSUE TITLE
Usage with functions?

### ISSUE THREAD

**Issue by grmkris** [dzhng/zod-gpt#8]
Can I use this Library to also invoke internal functions ? 
Like openai functions sdk allows

**Comment by mcapodici** [comment]
I would be up for making a PR for that. If it is wanted, and likely to get reviewed?

**Comment by dzhng** [comment]
You should be able to do this via the llm-api companion lib (https://github.com/dzhng/llm-api). It supports both function calling (via OpenAILegacy) or the new tool calling API.

I'm open to see if there are better ways to do this tho, so would def be happy to review any PRs!

**Comment by mcapodici** [comment]
Looks like you can with llm-api. I am new to both this repo and llm-api so didn't know that. I will give it a go!
